### ISSUE TITLE
Please accept gopher:// URLs

### ISSUE THREAD

**Issue by kseistrup** [dvkt/gild#6]
Funny error:

```sh
$ gild 'gopher://tilde.town/1/~lucidiot/contact'
bad hostname: Success
```

I expected `gild` to accept a valid gopher URL. I can see now that it doesn't.

I know I can

```sh
$ gild tilde.town 70 '/~lucidiot/contact'
```

but it's a bit cumbersome if you're given an URL in an email or a chat – it would be nice to be able to just copy and paste.

And I'm an bit curious: Which “Success” is `gild` talking about? :stuck_out_tongue_winking_eye:

**Comment by xvxx** [comment]
Yes, this is embarrassing. I think when I wrote GILD originally it was more difficult to work with strings in LDPL, that's why it makes you break up the URL and pass in pieces, but the situation is a lot better today. I'm just going to consider this a bug and fix it. 

> And I'm an bit curious: Which “Success” is gild talking about? 😜

The mysteries of Gopher are known only to few. We may never know.

(I will look into this too, I think the error handling was a bit buggy in the socket code before the switch to `getaddrinfo`.)

**Comment by xvxx** [comment]
Added in https://github.com/xvxx/gild/commit/d53af947?w=1. Pushing out a new release now. Thank you for the suggestion!
